### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by fabiocaccamo** [zagaran/django-migrate-or-rollback#2]
Hi @zagaran, 
I think this library is very useful and it should be the default django behaviour.

Any plans to add a test suite?

**Comment by zags** [comment]
We're unlikely to have time to add an automated test suite any time soon.  I'd be happy to review the addition of a test suite if you want to contribute.

Here's the tests we ran manually.  Start with a Django codebase with an existing database that is up to date with migrations, and run the following tests (rolling back to a saved database state after each test):

1. Add two new migrations that work.  Test that migrate_or_rollback successfully migrates.
2. Add two new migrations, the first of which works, the second of which doesn't.  Test that migrate_or_rollback rolls back to the initial database state and prints the stacktrace from the failed mitigation.
3. Add a new backwards compatible migration (such as changing the `blank` attribute on a field), run it, and then delete the migration file.  Then, repeat test 2. (This is to test that rollback rolls back to the latest migration that exists in the codebase).
4. Add new migrations to multiple apps with one migration that fails.  Test that migrate_or_rollback rolls back migrations on all apps.
